### ISSUE TITLE
"flora.cat" file (from Windows 8 signed driver) isn't here?

### ISSUE THREAD

**Issue by q2dg** [adafruit/Adafruit_Arduino_Boards#1]
Thanks!!

**Comment by tdicola** [comment]
Oh thanks for catching that issue, looks like I had the older Win 7 driver there.  Just updated with the latest driver that has both the inf and cat in this commit: https://github.com/adafruit/Adafruit_Arduino_Boards/commit/3310028b8de0fe0d186697e57af01e36dcdbd36f  Let me know if you see any issues, thanks!

**Comment by q2dg** [comment]
You're welcome!
