### ISSUE TITLE
avrdude.conf missing

### ISSUE THREAD

**Issue by morganrallen** [adafruit/Adafruit_Arduino_Boards#10]
I'm getting the following error on two different computers. One Linux, one OSX.

```
         System wide configuration file is ".../.arduino15/packages/adafruit/hardware/avr/1.4.9/bootloaders/gemma/avrdude.conf"
avrdude: can't open config file ".../.arduino15/packages/adafruit/hardware/avr/1.4.9/bootloaders/gemma/avrdude.conf": No such file or directory
avrdude: error reading system wide configuration file ".../.arduino15/packages/adafruit/hardware/avr/1.4.9/bootloaders/gemma/avrdude.conf"
```

Inspecting the package shows there isn't event a `bootloaders/gemma` directory. The only other close reference I find in issue #8. This repo also doesn't appear to ever have contained it.

I'm not even certain how this path is being attained, there's only one reference to `avrdude.conf` in `platforms.txt`.

I know the Arduino environment can be pretty aweful, any light shed on this would be appreciated.

**Comment by ladyada** [comment]
what IDE? what exact OS? more details please!

**Comment by morganrallen** [comment]
Linux running Arduino(.cc) 1.6.7
OSX (El Capitan) running latest Arduino, 1.6.11

Board manage using
https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

**Comment by ladyada** [comment]
try the latest IDE and reinstall the pkgs? i mean you're the only one with this issue :/

**Comment by morganrallen** [comment]
Both computer we've done full uninstalls of everything we can and reinstalled. What I don't understand here is this, `bootloaders/gemma` doesn't exist in this repo. How is it working for others? I guess I'll keep digging to figure out where this reference is coming from..

**Comment by ladyada** [comment]
i dont understand what do you need the bootloaders folder for - can you not upload to the gemma?

**Comment by morganrallen** [comment]
Nor do I. This is the behavior it does when we try to upload. I'd guessed
it was simply looking for the `avddude.conf` file in there.

**Comment by morganrallen** [comment]
And as a result, no, we cannot upload.

**Comment by ladyada** [comment]
we're using 1.6.9 so maybe try that?

**Comment by morganrallen** [comment]
OK, turns out this was part of a misunderstanding about Gemmas. This actually appears to be a bug in the Arduino Gemma, not the Adafruit Gemma. With some struggle still we got this working.

**Comment by rickjdev** [comment]
I'm seeing this, too. What did you do to resolve it?

I'm on Windows 10, arduino 1.6.11. I had last used adafruit''s IDE from 2014, and after installing 1.6.11 moved existing libraries out of the libraries directory except for the latest Adafruit_NeoPixel-master. I have an Adafruit GEMMA v2 in the USB. The Board chosen is Adafruit Gemma 8MHz. It compiles and verifies fine.

**Comment by rickjdev** [comment]
Cleared it somehow, by one or more of: uninstalling the IDE, renaming the old Documents/Arduino folder, removing the build folder from TEMP, removing the adafruit USB driver, reinstalling the IDE and drivers. I made sure to use a USB 2 hub (a harsh lesson from last time.) The last hiccup was that I forgot to set the Programmer to  USBtinyISP. Apparently all set now.
