### ISSUE TITLE
Adafruit SAMD Boards 1.4.1 does not install bossac 1.7.0

### ISSUE THREAD

**Issue by Alexia** [adafruit/Adafruit_Arduino_Boards#16]
**Problem:** Adafruit SAMD Boards 1.4.1 does not install bossac `1.7.0`.  Instead it installs bossac `1.8.0-48-gb176eee`.  The Feather M0 looks for bossac 1.7.0 when attempting to upload.

**Workaround:** Install Adafruit AVR Boards to get bossac 1.7.0 installed.

**Comment by ladyada** [comment]
hiya yeah you need to install Arduino SAM boards to get the compiler and such :) this is documented here
https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/using-with-arduino-ide#install-samd-support-6-5
