### ISSUE TITLE
"Invalid Library Found" with Adafruit SAMD 1.5.10

### ISSUE THREAD

**Issue by TheShadowhawke** [adafruit/Adafruit_Arduino_Boards#17]
I am using Arduino 1.8.11, and running into the following warning showing up in the compile window:

Invalid library found in C:\Users\<USER>\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.5.10\libraries\CI_Tests: no headers files (.h) found in C:\Users\<USER>\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.5.10\libraries\CI_Tests

This warning has started since installing the Adafruit SAMD boards version 1.5.10. It does not appear to affect compiling, but it does get spammed as the issue is detected.

**Comment by ladyada** [comment]
@hathach want to add a fake header to make it happy?
