### ISSUE TITLE
wrong PROTRINKET3FTDI board definition

### ISSUE THREAD

**Issue by cbxbiker61** [adafruit/Adafruit_Arduino_Boards#4]
--- ./boards.txt.orig   2015-09-25 09:10:59.000000000 -0600
+++ ./boards.txt        2015-09-27 17:17:02.343633679 -0600
@@ -191,7 +191,7 @@ protrinket3ftdi.build.mcu=atmega328p
 protrinket3ftdi.build.f_cpu=12000000L
 protrinket3ftdi.build.core=arduino:arduino
 protrinket3ftdi.build.variant=arduino:eightanaloginputs
-protrinket3ftdi.build.board=AVR_PROTRINKET5FTDI
+protrinket3ftdi.build.board=AVR_PROTRINKET3FTDI
 protrinket3ftdi.upload.tool=arduino:avrdude
 protrinket3ftdi.upload.protocol=arduino
 protrinket3ftdi.upload.maximum_size=28672

**Comment by toddtreece** [comment]
Updated in this repo & deployed v1.3.3 of the Adafruit AVR package with this commit: adafruit/arduino-board-index@f39e7e9d6c2bba7e841891735d5717b10a82775a

@cbxbiker61 thanks for the help!
