### ISSUE TITLE
pinToInterrupt not defined for 32u4 Boards

### ISSUE THREAD

**Issue by deisterhold** [adafruit/Adafruit_Arduino_Boards#7]
In all of the pins_arduino.h headers files the pinToInterrupt is not defined.

On line 72 in the pins_arduino.h the following needs to be added:
`#define digitalPinHasPWM(p)         ((p) == 3 || (p) == 5 || (p) == 6 || (p) == 9 || (p) == 10 || (p) == 11 || (p) == 13)`

`#define digitalPinToInterrupt(p) ((p) == 0 ? 2 : ((p) == 1 ? 3 : ((p) == 2 ? 1 : ((p) == 3 ? 0 : ((p) == 7 ? 4 : NOT_AN_INTERRUPT)))))`

The following files are missing this macro:
[Bluefruit Micro](https://github.com/adafruit/Adafruit_Arduino_Boards/blob/master/hardware/adafruit/avr/variants/bluefruitmicro/pins_arduino.h#L72)
[Generic 32u4](https://github.com/adafruit/Adafruit_Arduino_Boards/blob/master/hardware/adafruit/avr/variants/adafruit32u4/pins_arduino.h#L69)
[Circuit Play](https://github.com/adafruit/Adafruit_Arduino_Boards/blob/master/hardware/adafruit/avr/variants/circuitplay32u4/pins_arduino.h#L69)
[Feather](https://github.com/adafruit/Adafruit_Arduino_Boards/blob/master/hardware/adafruit/avr/variants/feather32u4/pins_arduino.h#L69)
[Flora](https://github.com/adafruit/Adafruit_Arduino_Boards/blob/master/hardware/adafruit/avr/variants/flora/pins_arduino.h#L69)

**Comment by ladyada** [comment]
updated, may be a few days until we repackage tho!
