### ISSUE TITLE
Where are the gemma bootloaders?

### ISSUE THREAD

**Issue by jeanbza** [adafruit/Adafruit_Arduino_Boards#8]
On my local machine I have:

`Applications/Arduino.app/Contents/Java/hardware/arduino/avr/bootloaders/gemma/avrdude.conf`

Is this not the right repo to go searching for this file?

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-Trinket-Gemma-Bootloader

**Comment by jeanbza** [comment]
Thank you! @ladyada
